### ISSUE TITLE
Texture replacement improvements for 1.15 (meta issue)

### ISSUE THREAD

**Issue by hrydgard** [hrydgard/ppsspp#17092]
# Plans for 1.15

- [x] Simplify state tracking (#17089)
- [x] Move all file reading to the thread, to avoid stutters even without zip. Avoid opening files twice (better performance) (#17091)
- [x] Bugfix basic mipmap support
- [x] Prepare for mipmapped texture file formats (reworked the cache a bit)
- [x] DDS support (desktop texture compression)
  - [x] Vulkan  (#17083)
  - [x] Other backends where possible
  - [x] Mipmaps
- [x] Universal texture compression - Basis/UASTC support through KTX [link](https://github.com/KhronosGroup/3D-Formats-Guidelines/blob/main/KTXDeveloperGuide.md). Will probably not bother supporting the .basis file format - "basisu.exe" can nicely generate .ktx files with both compression methods anyway, and it's likely the more future proof option.
- [x] Move texture size/format to the data cache (#17134, #17139)
- [x] Force mipmapping on, if present in replacement texture (#17144)
- [x] Verify thoroughly that clearing the cache doesn't corrupt textures or anything like that (see #16966)
- [x] Test and bugfix all of the above. There will be bugs :P
- [x] Document the new features

# Future plans

- [ ] Also support direct ETC/ASTC/BC through KTX (maybe)
- [ ] In Vulkan, offload image creation and the final upload to the thread, too! This is possible but will be a bit tricky with synchronization of the VRAM allocation.

**Comment by Gamemulatorer** [comment]
Texture replacement in zip file format doesn't work using the recently build https://github.com/hrydgard/ppsspp/commit/8e5825b7af34e4dc9c11eeb714ab465badbe6f43

**Comment by hrydgard** [comment]
Thanks, I'll check it out.

**Comment by hrydgard** [comment]
Should be fixed now.

**Comment by Gamemulatorer** [comment]
Replace texures disable/enable while in-game crashes the emulator.

```
F DEBUG   : Softversion: PD1930CF_EX_A_6.8.55
03-15 07:59:11.764 17235 17235 F DEBUG   : Time: 2023-03-15 07:59:11
03-15 07:59:11.764 17235 17235 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
03-15 07:59:11.764 17235 17235 F DEBUG   : Build fingerprint: 'vivo/1906/1906:11/RP1A.200720.012/compiler0316164337:user/release-keys'
03-15 07:59:11.764 17235 17235 F DEBUG   : Revision: '0'
03-15 07:59:11.764 17235 17235 F DEBUG   : ABI: 'arm64'
03-15 07:59:11.764 17235 17235 F DEBUG   : Timestamp: 2023-03-15 07:59:11+0800
03-15 07:59:11.764 17235 17235 F DEBUG   : pid: 16967, tid: 17041, name: EmuThread  >>> org.ppsspp.ppsspp <<<
03-15 07:59:11.764 17235 17235 F DEBUG   : uid: 10235
03-15 07:59:11.765 17235 17235 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x48
03-15 07:59:11.765 17235 17235 F DEBUG   : Cause: null pointer dereference
03-15 07:59:11.765 17235 17235 F DEBUG   :     x0  0000007dda08c900  x1  0000000000000000  x2  0000007df04056c0  x3  0000007d6dbbc700
03-15 07:59:11.765 17235 17235 F DEBUG   :     x4  0000000000000000  x5  0000007d6d76f108  x6  0000007e776a0000  x7  00000000011c4284
03-15 07:59:11.765 17235 17235 F DEBUG   :     x8  0000000000000000  x9  0000000064110a14  x10 0000007d80c11000  x11 000000000009dca9
03-15 07:59:11.765 17235 17235 F DEBUG   :     x12 0000000000000018  x13 00000003e8000000  x14 0025f1d2e6e3f5ce  x15 00009422911462a1
03-15 07:59:11.765 17235 17235 F DEBUG   :     x16 0000007d80f455e0  x17 0000007d80385c80  x18 0000007d80c4b384  x19 0000007dda08c900
03-15 07:59:11.765 17235 17235 F DEBUG   :     x20 0000007d69a88e40  x21 0000007d80f8c2c0  x22 0000007d6d772000  x23 0000007d80f5f318
03-15 07:59:11.765 17235 17235 F DEBUG   :     x24 0000007d80f5f318  x25 0000007d80f92278  x26 0000007d6d771ff8  x27 0000007dcf819c90
03-15 07:59:11.765 17235 17235 F DEBUG   :     x28 0000007d6d679000  x29 0000007d6d7717d0
03-15 07:59:11.765 17235 17235 F DEBUG   :     lr  0000007d8037f0d8  sp  0000007d6d7717a0  pc  0000007d80385cbc  pst 0000000080000000
03-15 07:59:11.776 17235 17235 F DEBUG   : backtrace:
03-15 07:59:11.776 17235 17235 F DEBUG   :       #00 pc 00000000006a9cbc  /data/app/~~d6O6PVI-qZIm1IRvDKpOJA==/org.ppsspp.ppsspp-AqTmhxQzhCZDpuH2iHAngg==/lib/arm64/libppsspp_jni.so (ReplacedTexture::PurgeIfOlder(double)+60) (BuildId: 5aea30fd6ff76f7bb1ef29906dd829be47abcc3f)
03-15 07:59:11.776 17235 17235 F DEBUG   :       #01 pc 00000000006a30d4  /data/app/~~d6O6PVI-qZIm1IRvDKpOJA==/org.ppsspp.ppsspp-AqTmhxQzhCZDpuH2iHAngg==/lib/arm64/libppsspp_jni.so (TextureReplacer::Decimate(ReplacerDecimateMode)+196) (BuildId: 5aea30fd6ff76f7bb1ef29906dd829be47abcc3f)
03-15 07:59:11.776 17235 17235 F DEBUG   :       #02 pc 00000000006a2e50  /data/app/~~d6O6PVI-qZIm1IRvDKpOJA==/org.ppsspp.ppsspp-AqTmhxQzhCZDpuH2iHAngg==/lib/arm64/libppsspp_jni.so (TextureReplacer::NotifyConfigChanged()+248) (BuildId: 5aea30fd6ff76f7bb1ef29906dd829be47abcc3f)
03-15 07:59:11.777 17235 17235 F DEBUG   :       #03 pc 00000000006bb66c  /data/app/~~d6O6PVI-qZIm1IRvDKpOJA==/org.ppsspp.ppsspp-AqTmhxQzhCZDpuH2iHAngg==/lib/arm64/libppsspp_jni.so (GPUCommon::CheckConfigChanged()+128) (BuildId: 5aea30fd6ff76f7bb1ef29906dd829be47abcc3f)
03-15 07:59:11.777 17235 17235 F DEBUG   :       #04 pc 00000000007d3b04  /data/app/~~d6O6PVI-qZIm1IRvDKpOJA==/org.ppsspp.ppsspp-AqTmhxQzhCZDpuH2iHAngg==/lib/arm64/libppsspp_jni.so (DrawGameBackground(UIContext&, Path const&, float, float, float, bool, bool)+132) (BuildId: 5aea30fd6ff76f7bb1ef29906dd829be47abcc3f)
03-15 07:59:11.777 17235 17235 F DEBUG   :       #05 pc 00000000007d47a0  /data/app/~~d6O6PVI-qZIm1IRvDKpOJA==/org.ppsspp.ppsspp-AqTmhxQzhCZDpuH2iHAngg==/lib/arm64/libppsspp_jni.so (UIDialogScreenWithGameBackground::DrawBackground(UIContext&)+176) (BuildId: 5aea30fd6ff76f7bb1ef29906dd829be47abcc3f)
03-15 07:59:11.777 17235 17235 F DEBUG   :       #06 pc 0000000000caf2ac  /data/app/~~d6O6PVI-qZIm1IRvDKpOJA==/org.ppsspp.ppsspp-AqTmhxQzhCZDpuH2iHAngg==/lib/arm64/libppsspp_jni.so (UIScreen::render()+164) (BuildId: 5aea30fd6ff76f7bb1ef29906dd829be47abcc3f)
03-15 07:59:11.777 17235 17235 F DEBUG   :       #07 pc 0000000000cae044  /data/app/~~d6O6PVI-qZIm1IRvDKpOJA==/org.ppsspp.ppsspp-AqTmhxQzhCZDpuH2iHAngg==/lib/arm64/libppsspp_jni.so (ScreenManager::render()+212) (BuildId: 5aea30fd6ff76f7bb1ef29906dd829be47abcc3f)
03-15 07:59:11.777 17235 17235 F DEBUG   :       #08 pc 00000000007b1374  /data/app/~~d6O6PVI-qZIm1IRvDKpOJA==/org.ppsspp.ppsspp-AqTmhxQzhCZDpuH2iHAngg==/lib/arm64/libppsspp_jni.so (NativeRender(GraphicsContext*)+468) (BuildId: 5aea30fd6ff76f7bb1ef29906dd829be47abcc3f)
03-15 07:59:11.777 17235 17235 F DEBUG   :       #09 pc 00000000007a77f8  /data/app/~~d6O6PVI-qZIm1IRvDKpOJA==/org.ppsspp.ppsspp-AqTmhxQzhCZDpuH2iHAngg==/lib/arm64/libppsspp_jni.so (UpdateRunLoopAndroid(_JNIEnv*)+40) (BuildId: 5aea30fd6ff76f7bb1ef29906dd829be47abcc3f)
03-15 07:59:11.777 17235 17235 F DEBUG   :       #10 pc 00000000007a99a8  /data/app/~~d6O6PVI-qZIm1IRvDKpOJA==/org.ppsspp.ppsspp-AqTmhxQzhCZDpuH2iHAngg==/lib/arm64/libppsspp_jni.so (BuildId: 5aea30fd6ff76f7bb1ef29906dd829be47abcc3f)
03-15 07:59:11.777 17235 17235 F DEBUG   :       #11 pc 000000000045ed1c  /data/app/~~d6O6PVI-qZIm1IRvDKpOJA==/org.ppsspp.ppsspp-AqTmhxQzhCZDpuH2iHAngg==/lib/arm64/libppsspp_jni.so (void* std::__ndk1::__thread_proxy<std::__ndk1::tuple<std::__ndk1::unique_ptr<std::__ndk1::__thread_struct, std::__ndk1::default_delete<std::__ndk1::__thread_struct> >, void (*)()> >(void*)+44) (BuildId: 5aea30fd6ff76f7bb1ef29906dd829be47abcc3f)
03-15 07:59:11.777 17235 17235 F DEBUG   :       #12 pc 00000000000f4510  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+64) (BuildId: b1d7ec252d7b460a539cf3a520c06bb8)
03-15 07:59:11.777 17235 17235 F DEBUG   :       #13 pc 000000000008ef34  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64) (BuildId: b1d7ec252d7b460a539cf3a520c06bb8)
```

**Comment by hrydgard** [comment]
Pushed a fix for that, I think.

**Comment by Gamemulatorer** [comment]
Still do experience crash if I enable/disable texture replacement.

https://user-images.githubusercontent.com/37603562/225327250-772fc560-9bbd-4dc8-8f1b-04c2cd82f64b.mp4

I'm using recently build https://github.com/hrydgard/ppsspp/commit/bcd6f4a88004af410a166c4ffbda015a7cbc851b

**Comment by hrydgard** [comment]
Alright, all the initial goals are done now. Closing this, might get back to the "future" ones later.
