### ISSUE TITLE
Indirect branch tracking CFI

### ISSUE THREAD

**Issue by bentley** [hrydgard/ppsspp#18246]
### Game or games this happens in

Multiple

### What area of the game / PPSSPP

IBT is a feature of newer Intel CPUs to implement CFI by explicitly marking valid branch destinations with `endbr`.

OpenBSD strictly enforces this feature on CPUs that support it. On such hardware, PPSSPP crashes as soon as I select a game (such as Cave Story).

There’s a backtrace, but even when PPSSPP is built with debug symbols it doesn’t seem helpful. I guess this means the crash is within the JIT.

```
Program terminated with signal SIGILL, Illegal instruction.
#0  0x000008d279da4012 in ?? ()
[Current thread is 1 (process 470761)]
(gdb) bt
#0  0x000008d279da4012 in ?? ()
#1  0x000008d29ad91da0 in ?? ()
#2  0x000008d29ad91da0 in ?? ()
#3  0x000000000152bec0 in ?? ()
#4  0x000008d29ad738b4 in Memory::g_arena ()
#5  0x000000000152bec0 in ?? ()
#6  0x000008d50f9f9660 in ?? ()
#7  0x0000000000000000 in ?? ()
```

### What should happen

JIT should generate `endbr` instructions in the appropriate places?

### Platform

Linux / BSD

### Mobile phone model or graphics card

Intel

### PPSSPP version affected

1.16.1

### Graphics backend (3D API)

OpenGL / GLES

### Checklist

- [X] Test in the [latest git build](https://buildbot.orphis.net/ppsspp/) in case it's already fixed.
- [X] [Search for other reports](https://github.com/hrydgard/ppsspp/search?q=my+issue&type=issues) of the same issue.
- [ ] Try resetting settings or older versions and include if the issue is related.
- [ ] Try without any cheats and without loading any save states.
- [ ] Include logs or screenshots of issue.

**Comment by hrydgard** [comment]
I don't have a CPU that supports it yet so can't test myself, and I'm not gonna try to implement this one blind. Contributions welcome though.

**Comment by unknownbrackets** [comment]
If you want to try testing this, you'd do something like:

1. In x64Emitter.cpp, add two methods: ENDBR64() and ENDBR32().
2. ENDBR64() should just call `Write8(0xF3); Write8(0x0F); Write8(0x1E); Write8(0xFA);` and 32 would be the same, but the last one would be 0xFB instead of 0xFA.
3. Add a new flag to CPUDetect.cpp, i.e. `bCET` or something, and for now just make it always true, i.e. `bool bCET = true;`.
4. In theory, all that's left is adding the `if (cpu_info.bCET) ENDBR64();` to the right places.  It's possible it's only needed after `enterDispatcher = AlignCode16();` in Asm.cpp and X64IRAsm.cpp, and then also after `b->normalEntry = GetCodePtr();` in Jit.cpp and `const u8 *blockStart = GetCodePointer();` in X64IRJit.cpp.  But it might be more places (though very possibly not), and you'll need to look at the assembly it crashes jumping to in a debugger to figure out where.

That would be mostly enough to get this working.  All that'd be left is to somehow detect when bCET should be true or false at that point.

-[Unknown]
